Resumos de SC
mendess/ResumosMIEI pull request #19
Opened 2020-05-09 12:36 UTC by matildeopbravo

2020-05-09 22:03 UTC, mendess commented on SC/memoria.md
> +## **Memória**
`## **Memória** (RAM)`

2020-05-09 22:08 UTC, matildeopbravo commented on SC/stack.md
> +A stack é uma estrutura de dados baseada no princípio *Last In First Out*, ou seja, o último valor a ser colocado é o primeiro a ser removido. Desta forma, é uma estrutura semelhante a uma *pilha*. N
mas o facto de eu ter mencionado que não é propriamente remover mas sim uma alteração do apontador que indica o topo da stack, não é o suficiente?

2020-05-09 22:09 UTC, matildeopbravo commented on SC/memoria.md
> +processamento, recorrendo aos barramentos, acede à memória. Desta
Eu planeio ter um ficheiro que explica as instruções básicas de assembly.

2020-05-09 22:09 UTC, mendess commented on SC/stack.md
> +A stack é uma estrutura de dados baseada no princípio *Last In First Out*, ou seja, o último valor a ser colocado é o primeiro a ser removido. Desta forma, é uma estrutura semelhante a uma *pilha*. N
Explicas mais a frente, certo? Entao ya. Is fine

2020-05-09 22:14 UTC, matildeopbravo commented on SC/stack.md
> +  ```mov %eax, (%esp)```
Irei adicionar uma explicação de assembly. Só estava com dificuldade em decidir a sequência com que explicaria isto porque acho que geralmente se ensina push e pop antes das outras instruções. Não queria deixar de explicar em que é que essas duas instruções consistem mas compreendo que precise de explicar a syntax de assembly também.

2020-05-09 22:17 UTC, mendess commented on SC/stack.md
> +  ```mov %eax, (%esp)```
Ya e uma dependencia circular. Nao ha uma "boa resposta" imo. O melhor que podes fazer e explicar logo a seguir.

Mas acho que consegues explicar a syntax sem explicar as instrucoes
`op arg1 arg2` mas deve ser tao abstrato que nao vai ter significado.

2020-05-09 22:34 UTC, matildeopbravo commented
Aqui diz qu

2020-05-09 22:36 UTC, matildeopbravo commented
Aqui aparece que sugeriste alterações mas não as consigo aceitar porque fui eu que fiz o pedido de pull request. Não há maneira de aceitar para alterar o meu fork?

2020-05-09 22:37 UTC, mendess commented
Continuas a fazer push normalmente

2020-09-23 11:19 UTC, mendess requested changes
Adoro os gifs que arranjaste, visualizar cenas ajuda me a mim e deve ajudar a
mais gente.

2020-09-25 00:03 UTC, matildeopbravo commented on SO/Ficha1.md
> +- Sempre que uma função mecionadas acima retorna um erro, o tipo de erro que
hahahahahhaha

2020-09-25 21:44 UTC, mendess requested changes

2020-09-25 21:44 UTC, mendess commented on SC/stack.md
> +* O **%esp** (stack pointer) é decrementado, uma vez que, ao ser adicionado um valor, o topo da stack altera-se.
Eu punha **decrementado** a negrito para reforçar que a stack cresce para baixo.

2020-09-25 21:44 UTC, mendess commented on SC/assembly.md
> +```mov (%eax), %ebx```
Acho que ficava bem ter uma explicacao mais "completa" da syntax dos `()`.
Podias colocar no fundo deste resumo numa secao a parte e aqui deixavas um link
para lá para não interromper esta explicacao.

2020-09-26 00:50 UTC, mendess approved these changes
Sera que era pedir muito passar a tabela `modos-enderecamento.png` para
markdown? Acho que a img se le um bocado mal.

2020-09-26 00:51 UTC, merged