Fixed assembly instruction in stack.md.
mendess/ResumosMIEI pull request #26
Opened 2021-06-19 19:28 UTC by matildeopbravo

2022-09-30 20:08 UTC, matildeopbravo commented
Já fiz isto há anos mas estava aberto ainda 😅

2022-10-01 12:58 UTC, mendess approved these changes

2022-10-01 14:16 UTC, mendess requested changes
Aquelas cena que sabes 👀

2022-10-01 20:56 UTC, mendess approved these changes

2022-10-02 00:28 UTC, merged